### ISSUE TITLE
Honeycomb farm page is not working

### ISSUE THREAD

**Issue by stabastian** [1Hive/honeycomb-subgraph#2]
When I enter to Farm page after unlocking my wallet I see this error in the console
![error](https://i.postimg.cc/4xPtHW4Q/error2.png)

Then when I try to access to one of the flowers, an error is shown in the console:
![error2](https://i.postimg.cc/k4djMjTF/error.png)

**Comment by onbjerg** [comment]
This is because you are on the wrong network or haven't set the chain ID to 100. This is not the correct repository to report it in either - please use #help on Discord in the future if you have trouble with something.
